name: Run Tests

on:
  workflow_call:
    inputs:
      dir-path:
        description: "Optional directory to point Ruff at. Default is project root: (.)"
        required: false
        type: string
        default: ""

      enable-pre-run-command:
        description: "Used to run a command before pytest runs, allowing you to fire off events that are required for your test to succeed."
        required: true
        type: boolean
        default: false

      pre-run-command:
        description: "The command to pass through to be run in the terminal."
        required: false
        type: string
        default: ""

jobs:
  validation-check:
    runs-on: ubuntu-latest
    steps:
      - name: validate pre run command
        if: ${{ inputs.enable-pre-run-command == true && inputs.pre-run-command == ""}}
        run: |
          echo "❌ ERROR: You must provide the 'pre-run-command' when 'enable-pre-run-command' is true."
          exit 1

  pytest-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Setup UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Run pre-run command
        if: ${{ inputs.enable-pre-run-commands }}
        run: bash -c "echo ⚙️ Running pre-run command:"
          bash -c "${{ inputs.pre-run-command }}"

      - name: Run tests
        run: uv run pytest ${{ inputs.dir-path }}