name: Run Type Check

on:
  workflow_call:
    inputs:
      dir-path:
        description: "Optional directory to for mypy to check. Default is {root}/src/"
        required: false
        type: string
        default: "src/"

jobs:
  type-checking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Setup UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Run MyPy
        run: uv run mypy ${{ inputs.dir-path }}